name: gesture_board
description: "gestureboard-combines-gestures-with-keyboard-mouse-control"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0  # Corrected indentation
  robot: ^0.1.3
  url_launcher: ^6.3.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/hand.png
